# Model
model: peleenet
interpolation: bilinear
batch_size: 128
sync_bn: true
# Optimizer
weight_decay: 1e-4
no_filter_bias_and_bn: true
# Learning rate schedule
lr: 0.18
warmup_lr: 0.0
min_lr: 0.0
epochs: 120
warmup_epochs: 0
cooldown_epochs: 0
# Augmentation & regularization
reprob: 0.0
smoothing: 0.0
# Misc
use_multi_epochs_loader: true
